name: Check build

on: [pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Install googletest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        sudo make -k -j all install

    - name: Build tests
      run: |
        make -k -j build-test

    - name: Run tests
      run: |
        make -k -j run-test

  cpplint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install cpplint.py
      run: |
        git clone https://github.com/google/styleguide.git

    - name: cpplint
      run: |
        make CPPLINT=styleguide/cpplint/cpplint.py -k -j cpplint

  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install cppcheck
      run: |
        sudo apt update
        sudo apt install cppcheck

    - name: cppcheck
      run: |
        make -k -j cppcheck
