name: Check build

on: [pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Init and update submodules
      run: |
        git submodule update -i

    - name: Build tests
      run: |
        make -k -j build-test

    - name: Run tests
      run: |
        make -k -j run-test

  cpplint:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install cpplint.py
      run: |
        git clone https://github.com/google/styleguide.git

    - name: cpplint
      run: |
        make CPPLINT=styleguide/cpplint/cpplint.py -k -j cpplint

  cppcheck:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install cppcheck
      run: |
        brew install cppcheck

    - name: cppcheck
      run: |
        make -k -j cppcheck
