name: Coverage report

on:
  pull_request:
  schedule:
    - cron:  0 20 * * *

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install gcovr
      run: |
        sudo apt update
        sudo apt install --no-install-recommends gcovr

    - name: Install googletest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake -DBUILD_GMOCK=OFF .
        sudo make -k -j all install

    - name: Generate coverage report
      run: |
        make BUILD_TYPE=coverage -k -j coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v1
      with:
        name: coverage_html
        path: out/coverage_report
