name: cppcheck

on:
  pull_request:
  schedule:
    - cron: 0 20 * * 5
  workflow_dispatch:

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cppcheck
        run: |
          sudo apt install cppcheck

      - name: Run cppcheck
        run: |
          make -k -j cppcheck
