name: cppcheck

on:
  pull_request:
  schedule:
    - cron:  0 20 * * 5

jobs:
  cppcheck:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
      CPPCHECK_MAKE_OPTIONS: -k -j MATCHCOMPILER=yes FILESDIR=/usr/share/cppcheck HAVE_RULES=yes CXXFLAGS='-O2 -DNDEBUG -Wall -Wno-sign-compare -Wno-unused-function'

    steps:
    - uses: actions/checkout@v2

    - name: Cache cppcheck (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      id: cache_cppcheck
      uses: actions/cache@v2
      with:
        path: cppcheck
        key: cppcheck_cache_${{ runner.os }}_v1

    - name: Clone cppcheck to install (Ubuntu)
      if: contains(matrix.os, 'ubuntu') && steps.cache_cppcheck.outputs.cache-hit != 'true'
      run: |
        git clone --depth=1 https://github.com/danmar/cppcheck.git

    - name: Build cppcheck (Ubuntu)
      if: contains(matrix.os, 'ubuntu') && steps.cache_cppcheck.outputs.cache-hit != 'true'
      run: |
        cd cppcheck
        sudo make ${{ env.CPPCHECK_MAKE_OPTIONS }} all

    - name: Install cppcheck (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        cd cppcheck
        sudo make ${{ env.CPPCHECK_MAKE_OPTIONS }} install

    - name: Run cppcheck
      run: |
        make -k -j cppcheck
