name: cppcheck

on:
  pull_request:
  schedule:
    - cron:  0 20 * * 5

jobs:
  cppcheck:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Clone cppcheck to install (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        git clone --depth=1 https://github.com/danmar/cppcheck.git

    - name: Install cppcheck (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        cd cppcheck
        sudo make -k -j MATCHCOMPILER=yes FILESDIR=/usr/share/cppcheck HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-sign-compare -Wno-unused-function" install

    - name: Install cppcheck (macOS)
      if: contains(matrix.os, 'macOS')
      run: |
        brew install cppcheck

    - name: Run cppcheck
      run: |
        make -k -j cppcheck
