name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Install gcovr
      run: |
        sudo pip3 install gcovr

    - name: Install graphviz and doxygen
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends graphviz doxygen

    - name: Install googletest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake -DBUILD_GMOCK=OFF -DCMAKE_CXX_STANDARD=11 .
        sudo make -k -j all install
        cd ..
        rm -rf googletest

    - name: Build site
      run: |
        make BUILD_TYPE=coverage -k -j site

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out/site
