name: Markdown lint

on:
  pull_request:
  schedule:
    - cron:  0 20 * * 5
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Lint markdown files.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actionshub/markdownlint@main
